name: Monolith
description: A custom API for handling many common tasks as well as some more unique ones. NMS Version ${spigot.version}
author: Schmoller, Narimm
version: ${plugin.version}

main: au.com.addstar.monolith.Monolith